# Generated by Django 3.2.11 on 2022-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QABoard',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=150)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('answer_title', models.TextField()),
                ('answer_content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'QABoard',
                'managed': False,
            },
        ),
    ]
