# Generated by Django 3.2.11 on 2022-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_class', models.IntegerField()),
                ('user_status', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user_sex', models.IntegerField()),
                ('user_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'Member',
                'managed': False,
            },
        ),
    ]
